services:
  # 1. Metrik Toplayıcı: Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: kale-prometheus
    restart: unless-stopped
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  # 2. Sunucu Donanım Ajanı: Node Exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: kale-node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"

  # 3. Log Deposu: Loki
  loki:
    image: grafana/loki:latest
    container_name: kale-loki
    restart: unless-stopped
    ports:
      - "3100:3100"

  # 4. Görselleştirme Ekranı: Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: kale-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ../monitoring/grafana/provisioning/alerting:/etc/grafana/provisioning/alerting:ro
      - ../monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - prometheus
      - loki
  alloy:
    image: grafana/alloy:latest
    container_name: kale-alloy
    restart: unless-stopped
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    volumes:
      - ../monitoring/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - ../app/logs:/var/log/app:ro
    ports:
      - "12345:12345"
    depends_on:
      - loki
  kale-app:
    build: ../app
    container_name: kale-app
    ports:
      - "3001:3000"
    volumes:
      - ../app/logs:/app/logs
volumes:
  grafana-data:
  prometheus-data:
